# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0003_auto_20160715_0028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name=b'Category')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'category', verbose_name=b'Image File')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name=b'Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Customer Email')),
                ('comments', models.TextField(verbose_name=b'Customer Comments')),
                ('image', models.ImageField(upload_to=b'', verbose_name=b'Customer Lock')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Stripe Id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name=b'Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'Description')),
                ('cost', models.FloatField(default=0, verbose_name=b'Cost')),
                ('time', models.IntegerField(default=60, verbose_name=b'Installation Time (minutes)')),
                ('image', models.ImageField(upload_to=b'item_images', verbose_name=b'Image')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctl.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housenumber', models.CharField(blank=True, max_length=30, verbose_name=b'House number/name')),
                ('street', models.CharField(blank=True, max_length=30, verbose_name=b'Street')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name=b'City')),
                ('post_code', models.CharField(blank=True, max_length=10, verbose_name=b'Post Code')),
                ('signature', models.TextField(blank=True)),
                ('additional_info', models.TextField(blank=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Item')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'job_image/')),
                ('stage', models.CharField(choices=[(b'pre', b'Pre'), (b'post', b'Post')], default=b'Pre', max_length=4)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Job')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_code', models.CharField(max_length=9, verbose_name=b'Post Code')),
                ('latitude', models.FloatField(blank=True, help_text=b'Google Maps calculated field based on Post Code', null=True, verbose_name=b'Latitude')),
                ('longitude', models.FloatField(blank=True, help_text=b'Google Maps calculated field based on Post Code', null=True, verbose_name=b'Longitude')),
                ('contractor', models.BooleanField(default=False, verbose_name=b'Contractor')),
                ('call_out_charge', models.FloatField(default=0, verbose_name=b'Call Out Charge')),
                ('mileage', models.IntegerField(default=10, help_text=b'Maximum distance from Post Code to Job Site', verbose_name=b'Max Travel (kilometers)')),
                ('stripe_user_id', models.CharField(blank=True, help_text=b"Stripe Token allowing access to contractor's stripe account", max_length=255, null=True, verbose_name=b'Stripe Token')),
                ('calendar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.Calendar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='item',
            field=models.ManyToManyField(through='ctl.Job_Item', to='ctl.Item', verbose_name=b'Items to be installed'),
        ),
    ]
