# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'contact/', verbose_name=b'Customer Lock')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
        migrations.AddField(
            model_name='contactimage',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Contact'),
        ),
    ]
