# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0002_auto_20170625_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5)),
                ('feedback', models.TextField()),
                ('customer', models.CharField(max_length=20)),
                ('priority', models.IntegerField(default=0, help_text=b'The 3 comments with the lowest number will be selected to show on the home screen')),
            ],
        ),
        migrations.AlterField(
            model_name='contactimage',
            name='image',
            field=models.ImageField(upload_to=b'contact', verbose_name=b'Customer Lock'),
        ),
        migrations.AlterField(
            model_name='jobimage',
            name='image',
            field=models.ImageField(upload_to=b'job_image'),
        ),
    ]
